### PR TITLE
install apollo-server-errors and import ApolloError from it in federation.js

### PR DESCRIPTION
**Pull request by wworrall**
Fix issue [#420](https://github.com/neo4j-graphql/neo4j-graphql-js/issues/420)

### CODE REVIEW

**Comment by wworrall** [comment]
Hi @johnymontana, I was wondering whether you could help.. The above test is failing but on inspection it seems to be a database connection error. Would you be able to shed any light on this?

Copied from [here](https://circleci.com/gh/neo4j-graphql/neo4j-graphql-js/7386?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

```
✖ before hook GraphQL error: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0. Caused by: connect ECONNREFUSED 127.0.0.1:7687

  Ran 1 test file out of 1 for job 1 of 1

  1 hook failed

  before hook

  /home/circleci/project/test/integration/gateway.test.js:39

   38: 
   39: 
   40: 

  GraphQL error: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0. Caused by: connect ECONNREFUSED 127.0.0.1:7687
```

**Comment by johnymontana** [comment]
Thanks @wworrall! Regarding the failing test, it seems the Gateway integration tests are a bit flaky on CircleCI, rerunning the failed workflow usually does the trick 🙃 It's on my list of things to fix :-)

**Comment by johnymontana** [comment]
@wworrall @emregency I went ahead and published this in v2.14.1-alpha.2 with the `@next` tag, which you can install with 

```
npm install neo4j-graphql-js@next
```

for testing. I'll cut a proper release sometime next week.

**Comment by emregency** [comment]
@johnymontana This works. Thanks.

P.S.: _Fragments still do not work with custom `@cypher` statements ref. #392_

**Comment by wworrall** [comment]
@johnymontana  thanks for merging and for your continued efforts.

**Comment by johnymontana** [comment]
Thanks folks! This fix is now published in v2.14.2

**Pull request merged**
