### PR TITLE
Interface handling: generate queries for interface types + FRAGMENT_TYPE fix

### PR DESCRIPTION
**Pull request by flazoon**
This set of changes addresses the following items:

1. Generate queries for interface types (but not mutations).
e.g.

interface Person {
  userId: ID!
  name: String
}
type User implements Person {
  userId: ID!
  name: String
  rated: [Rated]
}

type Query { 
  Person(
    userId: ID
    name: String
    _id: String
    first: Int
    offset: Int
    orderBy: [_PersonOrdering]
    filter: _PersonFilter
  ): [Person]  
  User(
    userId: ID
    name: String
    _id: String
    first: Int
    offset: Int
    orderBy: [_UserOrdering]
    filter: _UserFilter
  ): [User]
 
}

2. Fix an issue with FRAGMENT_TYPE value picking the first available label.
The fix follows the solution suggested here: https://github.com/neo4j-graphql/neo4j-graphql-js/pull/301#issuecomment-545159861

### CODE REVIEW

**Comment by johnymontana** [comment]
Hey @flazoon! Thanks so much for this PR! Would you mind pulling in the latest commits from master? Looks like we had a slight conflict with another PR.

But otherwise, this looks good to go!

**Comment by flazoon** [comment]
Thanks @johnymontana for the heads up, I've merged latest and fixed the conflicts.

**Comment by michaeldgraham** [comment]
This looks awesome @flazoon, thank you so much for your work on this! I'm sorry about the timing with PRs here - I hope the conflicts aren't too much of a hassle 🎉

**Comment by flazoon** [comment]
My pleasure to contribute @michaeldgraham. Always glad to see refactoring changes.

**Comment by johnymontana** [comment]
Perfect. Thanks @flazoon!

**Pull request merged**
